name: Daily Prediction Workflow

on:
  schedule:
    - cron: "30 7 * * *"  # This means 7:30 AM UTC every day
  workflow_dispatch: # You can also manually trigger the workflow

jobs:
  daily_prediction:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Use the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch Data from API and Make Prediction
        run: |
          python prediction.py

      - name: Commit Prediction Results to GitHub Pages
        run: |
          git config --global user.email "dey.piyal97@gmail.com"
          git config --global user.name "Piyal Dey"
          git add index.html
          git commit -m "Update prediction"
          git push origin gh-pages

