name: Daily Prediction Workflow

on:
  schedule:
    - cron: "30 7 * * *"  # This means 7:30 AM UTC every day
  workflow_dispatch: # You can also manually trigger the workflow

jobs:
  daily_prediction:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository on main branch
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Use the Python version you need

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Fetch Data from API and Make Prediction
      - name: Fetch Data from API and Make Prediction
        run: |
          python prediction.py  # This will update the index.html file with new predictions

      # Step 5: Checkout gh-pages branch
      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git reset --hard  # Ensure you're on a clean state

      # Step 6: Configure git user details
      - name: Configure git user
        run: |
          git config --global user.email "dey.piyal97@gmail.com"
          git config --global user.name "Piyal Dey"
          
      # Step 7: Commit updated index.html to gh-pages branch
      - name: Commit updated index.html to gh-pages
        run: |
          git add index.html  # Stage the file (no need to copy)
          git commit -m "Update prediction" || echo "No changes to commit"
          git push origin gh-pages  # Push to the gh-pages branch
